name: resource_monitor
description: A flutter plugin for Android and IOS to monitor CPU and RAM usage of device.
version: 1.0.0
homepage: https://github.com/diwesta/flutter_resource_monitor

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.diwesta.resource_monitor
        pluginClass: ResourceMonitorPlugin
      ios:
        pluginClass: ResourceMonitorPlugin